stages:
  - test
  - report

cache:
  key: composer-cache
  paths:
    - .composer-cache/

.test:
  before_script:
    - php -v
    # install system packages
    - apt-get update && apt-get install -y git unzip
    # install extensions
    - if [ "$COVERAGE" -eq 1 ]; then pecl install pcov; docker-php-ext-enable pcov; fi
    # install composer
    - php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer.sig');"
    - php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    - php -r '$expected = file_get_contents("/tmp/composer.sig"); $actual = hash_file("sha384", "/tmp/composer-setup.php"); exit(intval(!hash_equals($expected, $actual)));'
    - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - chmod +x /usr/local/bin/composer
    - rm /tmp/composer-setup.php /tmp/composer.sig
    # cache dependencies
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer update --ignore-platform-req=php
    - vendor/bin/phpunit

# main test matrix
test:
  extends: .test
  stage: test
  image: php:${PHP_VERSION}
  parallel:
    matrix:
      - PHP_VERSION:
          - '8.5-rc' # lowest version
#          - '8' # latest 8

# coverage
coverage:
  variables:
    COVERAGE: 1
  extends: .test
  stage: report
  only:
    - master
  image: php:8.5-rc
  script:
    - composer update
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover coverage.xml
    - bash <(curl -s https://codecov.io/bash)
